#### Задание r4z1:
Проверить гипотезу независимости признаков по критерию сопряженности хи-квадрат)
α = 0.1
Точки разбиения оси X (всего r + 1 интервал): r = 5
X1 = 114.05, Xr = 122.05
Точки разбиения оси Y (всего s + 1 интервал): s = 4
Y1 = 77.05, Ys = 83.05

In [6]:
from math import inf
import numpy as np
from scipy import stats
import pandas as pd
alf = 0.1
r = 5
s = 4


df1 = pd.read_csv("r4z1.csv")


def calc_n_i_j(i,j):
    x1 = x_split[i-1]
    x2 = x_split[i]
    y1 = y_split[j-1]
    y2 = y_split[j]
    return df1[(df1['X']<x2) & (df1['X']>x1) & (df1['Y']<y2)  & (df1['Y']>y1)]


n = len(df1['X'])
x_split = [-inf, 114.05, 116.05, 118.05, 120.05, 122.05, inf]
y_split = [-inf, 77.05, 79.05, 81.05, 83.05, inf]

n_con = np.array([[len(calc_n_i_j(i, j)) for j in range(1, s+2)] for i in range(1, r+2)])
nX = np.array([sum(s) for s in n_con])
nInv = n_con.transpose()
nY = np.array([sum(s) for s in nInv])
n_con = np.vstack([n_con, nY])
nX = np.append(nX, len(df1['X']))

n_df_con = pd.DataFrame(n_con, columns=['B1', 'B2', 'B3', 'B4', 'B5'], index=['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'nY'])


print(n_con)
print(nX)
print(nY)




n_df_con['nX'] = nX

T=0
for i in range(r+1):
    for m in range(s+1):
        T += ((n*n_con[i][m] - nX[i]*nY[m])**2) / (n*nX[i]*nY[m])
print('--------------')
print(n_df_con)

print(f"Уровень значимости = {alf}")

print(f"Статистика T = {T}")


critical = stats.chi2.ppf(1-alf,r*s)
#print(f"critical = {critical}")
p_value = 1 - stats.chi2.cdf(T,r*s)
print(f"Критический уровень значимости (p-value) = {p_value}")
if p_value > alf:
    print("H0 принимается")
else:
    print("H0 отклоняется")

[[ 5  3  4  2  1]
 [ 2  5  6  5  1]
 [ 4  3  5  5  4]
 [ 4  2  5  4  5]
 [ 0  2  5  1  2]
 [ 0  0  4  6  3]
 [15 15 29 23 16]]
[15 19 21 20 10 13 98]
[15 15 29 23 16]
--------------
    B1  B2  B3  B4  B5  nX
X1   5   3   4   2   1  15
X2   2   5   6   5   1  19
X3   4   3   5   5   4  21
X4   4   2   5   4   5  20
X5   0   2   5   1   2  10
X6   0   0   4   6   3  13
nY  15  15  29  23  16  98
Уровень значимости = 0.1
Статистика T = 21.760537886421158
Критический уровень значимости (p-value) = 0.35364462224920845
H0 принимается
